In [3]:
import numpy as np

In [4]:
# B15. 30부터 70까지 짝수로 이루어진 array를 만드시오 

In [5]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [6]:
# B13. 10개의 zero, 10개의 one, 10개의 5로 만들어진 array를 각각 만드시오

In [9]:
np.zeros((10,), int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((10,), int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.full((10,), 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
# B19. 15부터 55까지 수로 구성된 array에서 첫 요소와 마지막 요소를 제외하고 모두 print하는 코드를 작성하시오

In [15]:
a=np.arange(15,56)
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [16]:
# B20. 10부터 21까지 정수로 구성되는  3x4 array를 만드시오.

In [17]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [18]:
# B21. 5부터 50까지 10개의 요소를 등간격으로 구성하는 array를 만드시오 

In [19]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [20]:
# B22. 0-20까지 값을 가지는 array에서 9부터 15까지의 요소를 음수로 바꾸시오 

In [4]:
a=np.arange(0,21)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
a[9:16]*=-1

In [7]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [9]:
a[(a>=9) & (a<=15)] *= -1

In [10]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [33]:
# B23. 임의의 수로 이루어진 3x4 array를 생성하시오 

In [34]:
np.random.random((3,4))

array([[0.90793236, 0.85733275, 0.89944897, 0.7631485 ],
       [0.734717  , 0.33015013, 0.73615329, 0.45541908],
       [0.60777529, 0.87585508, 0.45447526, 0.08150006]])

In [35]:
# B24.(random.randint()) 0~100 중 임의의 integer 12개로 이루어진 3x4 array를 생성하시오 

In [36]:
np.random.randint(0,100, size=(3,4))

array([[90, 72, 20, 21],
       [87, 15, 76, 87],
       [51, 10, 88, 79]])

In [37]:
# B28. 10x10 array를 만들어 가운데는 zero 가장자리는 1로 채우시오 

In [48]:
a=np.ones((10,10), int)

In [49]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [50]:
a[1:9,1:9]*=0

In [51]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [52]:
# A90. 주어진 array에서 음수를 zero로 바꾸시오 

In [53]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

In [58]:
x[x<0]*=0

In [59]:
x

array([0, 0, 0, 2, 3, 4, 5, 0])

In [60]:
# A88. 6x6 random array를 만들어 .5보다 큰 요소는 값을 0.5로 바꾸시오.

In [64]:
f=np.random.random((6,6))

In [65]:
f

array([[0.08530755, 0.93935794, 0.59605854, 0.02914803, 0.20543958,
        0.74432635],
       [0.97862908, 0.07956713, 0.80374272, 0.48036057, 0.51601703,
        0.8094398 ],
       [0.85539332, 0.34082589, 0.82352887, 0.73963801, 0.13795754,
        0.2385465 ],
       [0.42692559, 0.84705549, 0.24546437, 0.00314637, 0.86330073,
        0.68126038],
       [0.3783499 , 0.16793881, 0.24023319, 0.49930409, 0.42040556,
        0.50664404],
       [0.24525685, 0.67092914, 0.49182304, 0.1425491 , 0.75076079,
        0.17515771]])

In [67]:
f[f>0.5]=0.5

In [68]:
f

array([[0.08530755, 0.5       , 0.5       , 0.02914803, 0.20543958,
        0.5       ],
       [0.5       , 0.07956713, 0.5       , 0.48036057, 0.5       ,
        0.5       ],
       [0.5       , 0.34082589, 0.5       , 0.5       , 0.13795754,
        0.2385465 ],
       [0.42692559, 0.5       , 0.24546437, 0.00314637, 0.5       ,
        0.5       ],
       [0.3783499 , 0.16793881, 0.24023319, 0.49930409, 0.42040556,
        0.5       ],
       [0.24525685, 0.5       , 0.49182304, 0.1425491 , 0.5       ,
        0.17515771]])